CREATE TABLE "push_subscriptions" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "push_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"endpoint" text NOT NULL,
	"p256dh" text NOT NULL,
	"auth" text NOT NULL,
	"user_agent" text,
	"last_used_at" timestamp with time zone,
	CONSTRAINT "push_subscriptions_user_endpoint_unique" UNIQUE("user_id","endpoint")
);
--> statement-breakpoint
ALTER TABLE "push_subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "web_notifications" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "web_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"conversation_id" bigint NOT NULL,
	"message_id" bigint,
	"note_id" bigint,
	"type" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"action_url" text NOT NULL,
	"sent_at" timestamp with time zone NOT NULL,
	"read_at" timestamp with time zone,
	"delivered_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "web_notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_id_idx" ON "push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "push_subscriptions_last_used_at_idx" ON "push_subscriptions" USING btree ("last_used_at");--> statement-breakpoint
CREATE INDEX "web_notifications_user_id_idx" ON "web_notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "web_notifications_conversation_id_idx" ON "web_notifications" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "web_notifications_user_sent_at_idx" ON "web_notifications" USING btree ("user_id","sent_at");--> statement-breakpoint
CREATE INDEX "web_notifications_read_at_idx" ON "web_notifications" USING btree ("read_at");