CREATE TABLE "issue_group_conditions" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_group_conditions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"issue_group_id" bigint NOT NULL,
	"saved_reply_id" bigint NOT NULL,
	"condition" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "issue_group_conditions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP INDEX "idx_messages_staff_drafts";--> statement-breakpoint
ALTER TABLE "issue_group_conditions" ADD CONSTRAINT "issue_group_conditions_issue_group_id_issue_groups_id_fk" FOREIGN KEY ("issue_group_id") REFERENCES "public"."issue_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_group_conditions" ADD CONSTRAINT "issue_group_conditions_saved_reply_id_saved_replies_id_fk" FOREIGN KEY ("saved_reply_id") REFERENCES "public"."saved_replies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "issue_group_conditions_issue_group_id_idx" ON "issue_group_conditions" USING btree ("issue_group_id");--> statement-breakpoint
CREATE INDEX "issue_group_conditions_saved_reply_id_idx" ON "issue_group_conditions" USING btree ("saved_reply_id");--> statement-breakpoint
CREATE INDEX "idx_messages_staff_drafts" ON "messages" USING btree ("conversation_id","status","draft_edited_at") WHERE ("messages"."deleted_at" is null and "messages"."status" = 'draft');