CREATE TABLE "issue_subgroups" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_subgroups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"issue_group_id" bigint NOT NULL,
	"title" text NOT NULL,
	"normalized_title" text NOT NULL,
	"description" text,
	"embedding" vector(1536),
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_by" text DEFAULT 'ai' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "issue_subgroups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversations_conversation" ADD COLUMN "issue_subgroup_id" bigint;--> statement-breakpoint
ALTER TABLE "issue_subgroups" ADD CONSTRAINT "issue_subgroups_issue_group_id_issue_groups_id_fk" FOREIGN KEY ("issue_group_id") REFERENCES "public"."issue_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "issue_subgroups_issue_group_id_normalized_title_unique" ON "issue_subgroups" USING btree ("issue_group_id","normalized_title");--> statement-breakpoint
CREATE INDEX "issue_subgroups_issue_group_id_created_at_idx" ON "issue_subgroups" USING btree ("issue_group_id","created_at");--> statement-breakpoint
CREATE INDEX "issue_subgroups_issue_group_id_idx" ON "issue_subgroups" USING btree ("issue_group_id");--> statement-breakpoint
CREATE INDEX "issue_subgroups_embedding_idx" ON "issue_subgroups" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
ALTER TABLE "conversations_conversation" ADD CONSTRAINT "conversations_conversation_issue_subgroup_id_issue_subgroups_id_fk" FOREIGN KEY ("issue_subgroup_id") REFERENCES "public"."issue_subgroups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversations_issue_subgroup_id_idx" ON "conversations_conversation" USING btree ("issue_subgroup_id");