CREATE TABLE "knowledge_gaps" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "knowledge_gaps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"query" text NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"last_seen_at" timestamp with time zone NOT NULL,
	"resolved_at" timestamp with time zone,
	"embedding" vector(1536)
);
--> statement-breakpoint
CREATE INDEX "knowledge_gaps_created_at_idx" ON "knowledge_gaps" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "knowledge_gaps_embedding_idx" ON "knowledge_gaps" USING hnsw ("embedding" vector_cosine_ops);